[DEFAULT]
# HOST: Listening Host (Default: localhost)
# PORT: Listening Port (Default: 5000)
# TEMP_DIR: Directory to save intermdeiate files temporarily (Default: ./temp_dir)
HOST=0.0.0.0
PORT=11451
TEMP_DIR=

[PADDLE_OCR]
# PADDLE_OCR_ROUTE: Route of paddle ocr (Default: /ocr)
PADDLE_OCR_ROUTE=

[TEXIFY]
# TEXIFY_ROUTE: Route of texify (Default: /texify)
TEXIFY_ROUTE=
